sudo: false
language: d
d:
  - dmd
  - ldc
env:
  - VERSION=min
  - VERSION=max
script:
  - rdmd ./test_with_libdparse.d -- dub test --compiler=$DC
  - rdmd ./test_with_libdparse.d -- dub build --config=lib --compiler=$DC
  - rdmd ./test_with_libdparse.d -- dub build --config=exe --compiler=$DC
